apiVersion: v1
kind: Pod
metadata:
  annotations:
    tke.cloud.tencent.com/networks-status: |-
      [{
          "name": "tke-bridge",
          "ips": [
              "172.20.1.109"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2021-01-29T14:32:38Z"
  name: presto-test-cluster-worker-5484658989-cx6l2-aaa
  namespace: default
spec:
  containers:
  - image: ccr.ccs.tencentyun.com/dlc_2020/tencent-dlc-presto:v1
    command:
    - sleep
    args:
    - 999d
    imagePullPolicy: Always
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - /usr/lib/presto/etc/pre-stop.sh
    name: presto-worker
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: "200m"
        memory: 100Mi
      requests:
        cpu: "200m"
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /usr/lib/presto/etc/pre-stop.sh
      name: config
      subPath: pre-stop.sh
    - mountPath: /usr/lib/presto/etc/config.properties
      name: config
      readOnly: true
      subPath: worker.config.properties
    - mountPath: /usr/lib/presto/etc/jmx.config
      name: config
      readOnly: true
      subPath: worker.jmx.config
    - mountPath: /usr/lib/presto/etc/node.properties
      name: config
      readOnly: true
      subPath: worker.node.properties
    - mountPath: /usr/lib/presto/etc/catalog/hive.properties
      name: catalog
      subPath: hive.properties
    - mountPath: /usr/lib/presto/etc/catalog/result.properties
      name: catalog
      subPath: result.properties
    - mountPath: /usr/lib/presto/etc/catalog/test1111
      name: catalog
      subPath: test1111
    - mountPath: /tmp/core-site.xml
      name: catalog
      subPath: presto.operator.coresite.core-site.xml
    - mountPath: /tmp/dynamic-core-site.xml
      name: catalog
      subPath: presto.operator.coresite.dynamic-core-site.xml
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-7ksqf
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: 10.0.8.39
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsUser: 1000
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - configMap:
      defaultMode: 420
      name: presto-test-cluster-presto-configmap
    name: config
  - configMap:
      defaultMode: 420
      name: presto-test-cluster-catalog-configmap
    name: catalog
  - name: default-token-7ksqf
    secret:
      defaultMode: 420
      secretName: default-token-7ksqf
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-01-29T14:32:38Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-01-29T14:39:33Z"
    message: 'containers with unready status: [presto-worker]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-01-29T14:39:33Z"
    message: 'containers with unready status: [presto-worker]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-01-29T14:32:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://a255869c9072fed81ebade7f52918ebaf368447530144a1637184c6cef13c6f9
    image: ccr.ccs.tencentyun.com/dlc_2020/tencent-dlc-presto:v1
    imageID: docker-pullable://ccr.ccs.tencentyun.com/dlc_2020/tencent-dlc-presto@sha256:eed107fe7d0ab4489a84915f8cb8a17d39ee593948764022aae83201fc1198c8
    lastState:
      terminated:
        containerID: docker://a255869c9072fed81ebade7f52918ebaf368447530144a1637184c6cef13c6f9
        exitCode: 1
        finishedAt: "2021-01-29T14:39:32Z"
        reason: Error
        startedAt: "2021-01-29T14:39:21Z"
    name: presto-worker
    ready: false
    restartCount: 6
    state:
      waiting:
        message: Back-off 5m0s restarting failed container=presto-worker pod=presto-test-cluster-worker-5484658989-cx6l2_default(d6456081-623e-11eb-8098-6e638ff50718)
        reason: CrashLoopBackOff
  hostIP: 10.0.8.39
  phase: Running
  podIP: 172.20.1.109
  qosClass: Guaranteed
  startTime: "2021-01-29T14:32:38Z"
